pipeline:
  identifier: Build_rahultyagi624_reactcalculator_1703861406232
  name: Build reactcalculator
  orgIdentifier: default
  projectIdentifier: js_demo
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1698398634837
        repoName: rahultyagi624/reactcalculator
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: npminstall
                  name: npm_install
                  spec:
                    command: npm install
                  timeout: ""
                  type: Run
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
        type: CI
    - stage:
        name: build and push to docker
        identifier: build_and_push_to_docker
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: BuildAndPushDockerRegistry
                  name: BuildAndPushDockerRegistry_1
                  identifier: BuildAndPushDockerRegistry_1
                  spec:
                    connectorRef: js_demo
                    repo: js-demo
                    tags:
                      - "19"
